### ISSUE TITLE
where is the leaderboard?

### ISSUE THREAD

**Issue by zhuqunxi** [efficientqa/efficientqa.github.io#1]
where is the leaderboard? I can not fiind it. Thanks.

**Comment by tomkwiat** [comment]
Hi, we're sorry that the leaderboard is not yet up. We plan to have it out in the coming weeks. 

To be notified of when that happens, please sign up to the EfficientQA mailing list : https://efficientqa.github.io/sign_up_for_notifications.html

**Comment by zhuqunxi** [comment]
> Hi, we're sorry that the leaderboard is not yet up. We plan to have it out in the coming weeks.
> 
> To be notified of when that happens, please sign up to the EfficientQA mailing list : https://efficientqa.github.io/sign_up_for_notifications.html

Thanks for your help.

**Comment by tomkwiat** [comment]
The leaderboard is now live at https://ai.google.com/research/NaturalQuestions/efficientqa and we have published detailed submission instructions at https://efficientqa.github.io/submit.html.
